# Generated by Django 4.2.4 on 2023-08-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
